---
-  hosts: all  
   become: yes
   tasks:
   - name: updating packages
     apt:
     update_cache: yes
     hello
hello










---
- hosts: all  
  become: yes
  tasks:
  - name: updating packages
    apt:
      update_cache: yes
  - name: installing nginxserver
    apt: 
       name: nginx
       state: present
    
